repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0  # pick a git hash / tag to point to
    hooks:
      - id: flake8